name: flutter_ble_logger
description: BLE Logger for MobileNLD-FL Research Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # BLE functionality
  flutter_blue_plus: ^1.35.5
  
  # Permissions
  permission_handler: ^12.0.1
  
  # File operations
  path_provider: ^2.1.5
  
  # CSV operations
  csv: ^6.0.0
  
  # State management
  provider: ^6.1.5+1
  
  # Date formatting
  intl: ^0.20.2
  
  # File sharing
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true